on:
  push:
    tags:
      - 'v*'
    branches:
      - prerelease

permissions:
  contents: read
  packages: write

jobs:
  builder-image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - run: make builder
