on:
  push:
    tags:
      - 'v*'

jobs:
  builder-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - run: make builder
