on:
  push:
    branches:
      - master

jobs:
  builder-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - run: make builder
