on:
  push:
    tags:
      - 'v*'
      - prerelease

jobs:
  builder-image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - run: make builder
